### ISSUE TITLE
Provide administration meta information in Tarantool config

### ISSUE THREAD

**Issue by georgiy-belyanin** [georgiy-belyanin/ttx#11]
Current implementation of the Tarantool config doesn't involve any way to determine the most appropriate parameters for connecting to instance. The URI of the instance is determined by the heuristic from the parameters that aren't related to administration (see https://github.com/georgiy-belyanin/ttx/blob/b1631b271f99bd6a4255e0533673a2d76b0bfd5f/config/instance.go). It's not so nice because it uses URIs that's advertised for other purposes. It also makes it hard to determine whether the instance is running locally or not.

It'd nice to have a way to determine a login and a uri that is exactly the best one to be used by an administrator. Possibly, it can be done by adding `iproto.advertise.admin` into Tarantool.

```yaml
iproto:
  advertise:
    admin:
      login: 'admin'
      uri: 'localhost:3301'
      params: []
```

Suggested by @Totktonada
